FROM node:24-slim AS base 

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV PNPM_CONFIG_NO_TTY=1
ENV CI=true

RUN corepack enable
COPY . /app
WORKDIR /app

ARG VITE_GOOGLE_CLIENT_EMAIL
ARG VITE_GOOGLE_PRIVATE_KEY


FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install  --frozen-lockfile
RUN pnpm run build 

FROM base
COPY --from=prod-deps /app/node_modules node_modules/
COPY --from=build /app/build build/
EXPOSE 4174
CMD [ "pnpm", "start" ]

