/**
 * The SvelteKit app, as adapter-node builds it: an Express-compatible middleware that serves every
 * route, endpoint and static asset.
 *
 * The specifier is held in a variable so TypeScript does not follow it. `build/` is generated by
 * `vite build` and is not in the repository, so a static import is unresolvable on a clean
 * checkout — and once it *has* been built, `checkJs` would turn the whole bundled output into
 * three thousand type errors. Neither is a real problem with this code, and both would end with
 * the deployed entrypoint being excluded from the type check again, which is how it came to ship
 * broken in the first place. One deliberately opaque import buys a type-checked entrypoint.
 */
import type { RequestHandler } from 'express';

const generatedHandler = '../build/handler.js';

export const { handler } = (await import(generatedHandler)) as { handler: RequestHandler };
