// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: cyd-interface

#include "ui.h"

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Header = ui_Header_create(ui_Home);
    lv_obj_set_x(ui_Header, -1);
    lv_obj_set_y(ui_Header, -107);

    ui_ExpertiseButton = lv_button_create(ui_Home);
    lv_obj_set_width(ui_ExpertiseButton, 70);
    lv_obj_set_height(ui_ExpertiseButton, 70);
    lv_obj_set_x(ui_ExpertiseButton, -70);
    lv_obj_set_y(ui_ExpertiseButton, -35);
    lv_obj_set_align(ui_ExpertiseButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ExpertiseButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ExpertiseButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ExpertiseButton, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ExpertiseButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ExpertiseButton, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ExpertiseButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ExpertiseButtonImage = lv_image_create(ui_ExpertiseButton);
    lv_image_set_src(ui_ExpertiseButtonImage, &ui_img_user_png);
    lv_obj_set_width(ui_ExpertiseButtonImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExpertiseButtonImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExpertiseButtonImage, 0);
    lv_obj_set_y(ui_ExpertiseButtonImage, -5);
    lv_obj_set_align(ui_ExpertiseButtonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ExpertiseButtonImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ExpertiseButtonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExpertiseButtonLabel = lv_label_create(ui_ExpertiseButton);
    lv_obj_set_width(ui_ExpertiseButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ExpertiseButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ExpertiseButtonLabel, 0);
    lv_obj_set_y(ui_ExpertiseButtonLabel, 24);
    lv_obj_set_align(ui_ExpertiseButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ExpertiseButtonLabel, "Expertise");
    lv_obj_set_style_text_font(ui_ExpertiseButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImplantsButton = lv_button_create(ui_Home);
    lv_obj_set_width(ui_ImplantsButton, 70);
    lv_obj_set_height(ui_ImplantsButton, 70);
    lv_obj_set_x(ui_ImplantsButton, 70);
    lv_obj_set_y(ui_ImplantsButton, -35);
    lv_obj_set_align(ui_ImplantsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImplantsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ImplantsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ImplantsButton, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImplantsButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImplantsButton, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_ImplantsButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_ImplantButtonImage = lv_image_create(ui_ImplantsButton);
    lv_image_set_src(ui_ImplantButtonImage, &ui_img_1577569611);
    lv_obj_set_width(ui_ImplantButtonImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImplantButtonImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImplantButtonImage, 0);
    lv_obj_set_y(ui_ImplantButtonImage, -5);
    lv_obj_set_align(ui_ImplantButtonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImplantButtonImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImplantButtonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImplantsButtonLabel = lv_label_create(ui_ImplantsButton);
    lv_obj_set_width(ui_ImplantsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ImplantsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ImplantsButtonLabel, 0);
    lv_obj_set_y(ui_ImplantsButtonLabel, 25);
    lv_obj_set_align(ui_ImplantsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ImplantsButtonLabel, "Implants");
    lv_obj_set_style_text_font(ui_ImplantsButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MessagesButton = lv_button_create(ui_Home);
    lv_obj_set_width(ui_MessagesButton, 70);
    lv_obj_set_height(ui_MessagesButton, 70);
    lv_obj_set_x(ui_MessagesButton, 0);
    lv_obj_set_y(ui_MessagesButton, 50);
    lv_obj_set_align(ui_MessagesButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MessagesButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MessagesButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MessagesButton, lv_color_hex(0x3D3D3D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MessagesButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MessagesButton, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MessagesButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MessagesButtonImage = lv_image_create(ui_MessagesButton);
    lv_image_set_src(ui_MessagesButtonImage, &ui_img_9038990);
    lv_obj_set_width(ui_MessagesButtonImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessagesButtonImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MessagesButtonImage, 0);
    lv_obj_set_y(ui_MessagesButtonImage, -5);
    lv_obj_set_align(ui_MessagesButtonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MessagesButtonImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MessagesButtonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MessagesButtonLabel = lv_label_create(ui_MessagesButton);
    lv_obj_set_width(ui_MessagesButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MessagesButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MessagesButtonLabel, 0);
    lv_obj_set_y(ui_MessagesButtonLabel, 25);
    lv_obj_set_align(ui_MessagesButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MessagesButtonLabel, "Messages");
    lv_obj_set_style_text_font(ui_MessagesButtonLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ExpertiseButton, ui_event_ExpertiseButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImplantsButton, ui_event_ImplantsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MessagesButton, ui_event_MessagesButton, LV_EVENT_ALL, NULL);

}
